Repository blocto/sdk-toolkit, pull requests merged in 2024-01, with the labels that each got.

#80 Feat/evm batch tx editor
  src/components/EvmEditor.tsx
  src/components/EvmEditors/EvmBatchTxEditor.tsx
  src/components/EvmEditors/EvmSendEditor.tsx
  src/components/EvmEditors/EvmTxForm.tsx
  src/components/EvmEditors/EvmUserOpEditor.tsx
Labels: Feature

#87 Fix: evm editor improve
  src/components/EvmChainSelect.tsx
  src/components/EvmEditors/EvmTxForm.tsx
Labels: BugFix

#88 Fix/adjust revert default value
  src/components/EvmEditors/EvmBatchTxEditor.tsx
Labels: bug, BugFix

#90 fix: build warning
  src/components/EvmChainSelect.tsx
Labels: BugFix

#91 fix: send batch transactions
  src/components/EvmEditors/EvmBatchTxEditor.tsx
Labels: BugFix
